# Generated by Django 3.2.6 on 2022-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ready',
        ),
        migrations.AddField(
            model_name='question',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
